cloud:
  aws:
    credentials:
      access-key: AKIASJN66YSZDB7SKVBJ
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: hotel-management


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

